#!/usr/bin/env node
// Generate a QuickStatements batch from the article pages.
// Output: wikidata-batch.txt — paste at https://quickstatements.toolforge.org/
//
// Walks src/pages/articles/, extracts each ArticleLayout's props, joins with
// scripts/wikidata-known.json, and emits CREATE blocks for new items plus
// augmentation statements for items that already exist on Wikidata.

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, basename } from 'path';

const cfg = JSON.parse(readFileSync('scripts/wikidata-known.json', 'utf8'));
const ARTICLES_DIR = 'src/pages/articles';
const OUT_FILE = 'wikidata-batch.txt';

function decodeHTML(s) {
  return s
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&apos;/g, "'")
    .replace(/&#39;/g, "'");
}

function parseStringProp(content, name) {
  const re = new RegExp(`\\s${name}="([^"\\n]*)"`);
  const m = content.match(re);
  return m ? decodeHTML(m[1]) : null;
}

function parseArrayProp(content, name) {
  const re = new RegExp(`${name}=\\{(\\[[\\s\\S]*?\\])\\}`);
  const m = content.match(re);
  if (!m) return null;
  try {
    return JSON.parse(decodeHTML(m[1]));
  } catch {
    return null;
  }
}

function parseArticle(filepath) {
  const content = readFileSync(filepath, 'utf8');
  const slug = basename(filepath, '.astro');
  return {
    slug,
    title: parseStringProp(content, 'title'),
    authors: parseArrayProp(content, 'authors') || [],
    journal: parseStringProp(content, 'journal'),
    volume: parseStringProp(content, 'volume'),
    year: parseStringProp(content, 'year'),
    publishDate: parseStringProp(content, 'publishDate'),
    doi: parseStringProp(content, 'doi'),
    ssrnUrl: parseStringProp(content, 'ssrnUrl'),
    pdfUrl: parseStringProp(content, 'pdfUrl'),
  };
}

function ssrnIdFromUrl(url) {
  if (!url) return null;
  const m = url.match(/abstract_id=(\d+)/i) || url.match(/abstract\/(\d+)/i);
  return m ? m[1] : null;
}

function ssrnDoi(url) {
  const id = ssrnIdFromUrl(url);
  return id ? `10.2139/ssrn.${id}` : null;
}

function extractYear(art) {
  for (const v of [art.publishDate, art.year]) {
    if (v) {
      const m = String(v).match(/\d{4}/);
      if (m) return m[0];
    }
  }
  return null;
}

function esc(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

const out = [];
const emit = (line = '') => out.push(line);

emit('# Wikidata QuickStatements batch — Andrea Tosato articles');
emit('# Generated by scripts/wikidata-export.mjs — do not edit by hand');
emit('# Paste at https://quickstatements.toolforge.org/  →  "Run"');
emit('# CREATE blocks add new items. Q-prefixed lines augment existing items.');
emit('');
emit('# ============================================');
emit('# 1. NEW SCHOLARLY ARTICLE ITEMS');
emit('# ============================================');

const articleFiles = readdirSync(ARTICLES_DIR)
  .filter(f => f.endsWith('.astro'))
  .sort()
  .map(f => join(ARTICLES_DIR, f));

let createdCount = 0;
let skippedCount = 0;
let warnings = [];

for (const f of articleFiles) {
  const art = parseArticle(f);

  if (!art.title) {
    warnings.push(`Could not parse title from ${f}`);
    emit(`# WARN: could not parse title from ${f} — skipping`);
    continue;
  }

  if (cfg.skip[art.slug]) {
    skippedCount++;
    emit(`# Skip ${art.slug} — already exists as ${cfg.skip[art.slug]}`);
    continue;
  }

  emit('');
  emit(`# ${art.title}  (${art.slug})`);
  emit('CREATE');
  emit(`LAST\tP31\tQ13442814`); // instance of: scholarly article
  emit(`LAST\tLen\t"${esc(art.title)}"`);

  const yr = extractYear(art);
  const desc = [
    yr,
    art.journal || 'law review',
    'article',
    art.authors.length > 1 ? '(co-authored)' : null,
  ].filter(Boolean).join(' ');
  emit(`LAST\tDen\t"${esc(desc)}"`);

  for (const author of art.authors) {
    if (author === 'Andrea Tosato') {
      emit(`LAST\tP50\t${cfg.tosato_qnumber}`);
    } else {
      emit(`LAST\tP2093\t"${esc(author)}"`);
    }
  }

  if (art.journal) {
    const jq = cfg.journals[art.journal];
    if (jq) {
      emit(`LAST\tP1433\t${jq}`);
    } else {
      emit(`# WARN: no Q-number for "${art.journal}" — P1433 omitted`);
      warnings.push(`No Q-number for journal "${art.journal}" (article: ${art.slug})`);
    }
  }

  if (art.volume) {
    emit(`LAST\tP478\t"${esc(art.volume)}"`);
  }

  if (yr) {
    emit(`LAST\tP577\t+${yr}-00-00T00:00:00Z/9`);
  }

  emit(`LAST\tP407\tQ1860`); // language: English
  emit(`LAST\tP953\t"https://www.andreatosato.com/articles/${art.slug}/"`);

  const doi =
    art.doi ||
    (cfg.manual_dois && cfg.manual_dois[art.slug]) ||
    ssrnDoi(art.ssrnUrl);
  if (doi) {
    emit(`LAST\tP356\t"${doi}"`);
  }

  const ssrnId = ssrnIdFromUrl(art.ssrnUrl);
  if (ssrnId) {
    emit(`LAST\tP893\t"${ssrnId}"`);
  }

  createdCount++;
}

emit('');
emit('# ============================================');
emit('# 2. AUGMENTATIONS TO EXISTING ITEMS');
emit('# ============================================');

if (cfg.skip['debt-tokens']) {
  const dt = cfg.skip['debt-tokens'];
  emit('');
  emit(`# Debt Tokens (${dt}) — add missing co-authors, DOI, slashed URL`);
  emit(`# NOTE: Wikidata already has the unslashed URL on P953. After running, manually delete that statement and keep only the slashed one.`);
  emit(`${dt}\tP2093\t"Diane Lourdes Dick"`);
  emit(`${dt}\tP2093\t"Christopher K. Odinet"`);
  emit(`${dt}\tP356\t"10.2139/ssrn.4694629"`);
  emit(`${dt}\tP953\t"https://www.andreatosato.com/articles/debt-tokens/"`);
}

emit('');
emit(`# Andrea Tosato (${cfg.tosato_qnumber}) — cross-link augmentations`);
emit(`${cfg.tosato_qnumber}\tP2002\t"Andrea_Tosato"`);                       // Twitter
emit(`${cfg.tosato_qnumber}\tP6634\t"andrea-tosato-5a862067"`);              // LinkedIn personal profile ID
emit(`${cfg.tosato_qnumber}\tAen\t"A. Tosato"`);                             // alias
emit(`${cfg.tosato_qnumber}\tAen\t"Andrea Tosato (jurist)"`);                // alias

writeFileSync(OUT_FILE, out.join('\n') + '\n');

console.log(`Wrote ${OUT_FILE}`);
console.log(`  CREATE blocks: ${createdCount}`);
console.log(`  Skipped (already exists): ${skippedCount}`);
console.log(`  Augmentations: 2 items`);
if (warnings.length) {
  console.log(`  Warnings: ${warnings.length}`);
  for (const w of warnings) console.log(`    - ${w}`);
}
